(define (make-segment start end)
  (cons start end))

(define (start-segment segment)
  (car segment))
(define (end-segment segment)
  (cdr segment))

(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")")
  (newline))

(define (midpoint-segment segment)
  (cons 
    (avg (x-point (start-segment segment))
	 (x-point (end-segment segment)))
    (avg (y-point (start-segment segment))
	 (y-point (end-segment segment)))))
(define (avg x y)
  (/ (+ x y) 2))

(let ((start (make-point 1 2))
      (end   (make-point 2 3)))
  (begin (display "start point: ")
  (print-point start)
  (display "end   point: ") 
  (print-point end))
  (display "middle point: ")
  (print-point (midpoint-segment (make-segment start end))))
